# Generated by Django 4.1 on 2023-02-08 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/blog/', verbose_name='Image')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('short_content', models.TextField(verbose_name='short description')),
                ('content', models.TextField(verbose_name='content')),
                ('date', models.DateField(auto_now_add=True)),
                ('keyword', models.CharField(max_length=100, verbose_name='keywords for SEO')),
                ('description', models.CharField(max_length=100, verbose_name='description for SEO')),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', max_length=200, unique=True, verbose_name='Ссылка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Posts',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('blog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.postblog')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
    ]
