# Generated by Django 4.1 on 2023-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='blog',
        ),
        migrations.AddField(
            model_name='category',
            name='blog',
            field=models.ManyToManyField(default=None, to='blog.postblog'),
        ),
    ]
